sudo: required

language: generic

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

services:
  - docker

matrix:
  include:
  # BBuild on Linux with docker
  - env: BUILD=stack ARGS=""
    compiler: ": #stack default"

  # Build on macOS natively
  - env: BUILD=stack ARGS=""
    compiler: ": #stack default osx"
    os: osx


before_install:
  # Using compiler above sets CC to an invalid value, so unset it
  - unset CC
  # We want to always allow newer versions of packages when building on GHC HEAD
  - CABALARGS=""
  - if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi

  - |
    if [ `uname` = "Darwin" ]
    then
      # Download and unpack the stack executable
      export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
      mkdir -p ~/.local/bin

      travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin

      # Use the more reliable S3 mirror of Hackage
      mkdir -p $HOME/.cabal
      echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
      echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config
    
    else
      docker pull nilrecurring/haskell-lavello:lts-12
      docker run --mount src="$(pwd)",target=/home/ubuntu/spacchetti,type=bind nilrecurring/haskell-lavello:lts-12 /bin/bash -c "sudo chown -R ubuntu spacchetti; cd spacchetti; stack build"
    
    fi


install:
  - |
    if [ `uname` = "Darwin" ]
    then

      echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
      if [ -f configure.ac ]; then autoreconf -i; fi

      set -ex
      stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
      set +ex
    
    else

      echo "Skipping install on Linux"

    fi


script:
  - |
    if [ `uname` = "Darwin" ]
    then

      set -ex
      stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
      set +ex

    else

      echo "Skipping install on Linux"

    fi


before_deploy:
  - |
    if [ `uname` = "Darwin" ]
    then
      stack build --copy-bins --local-bin-path ./artifacts;
    else
      docker run --mount src="$(pwd)",target=/home/ubuntu/spacchetti,type=bind nilrecurring/haskell-lavello:lts-12 /bin/bash -c "cd spacchetti; stack build --copy-bins --local-bin-path ./artifacts"
    fi
  - cp artifacts/spacchetti spacchetti
  - tar -zcvf "${TRAVIS_OS_NAME}.tar.gz" spacchetti

deploy:
  provider: releases
  api_key: $API_KEY
  file:
    - $TRAVIS_OS_NAME.tar.gz
  skip_cleanup: true
  on:
    tags: true
