version: 1.0.{build}

branches:
  only:
  - master

environment:
  STACK_ROOT: C:\sr
  STACK_VERSION: 2.1.1

  # Workaround a gnarly bug https://github.com/haskell/cabal/issues/5386
  # See: https://www.fpcomplete.com/blog/2018/06/sed-a-debugging-story
  # TODO: check if it's fixed once we switch to lst-13 and GHC 8.6
  TMP: "c:\\tmp"

  matrix:
    - STACK_YAML: stack.yaml

install:
  - choco install -y haskell-stack --version %STACK_VERSION%
  - stack setup > nul
  - choco install psc-package
  - npm install -g bower
  - ps: |
      $releases = "https://api.github.com/repos/purescript/purescript/releases"
      $tag = "v0.13.3"
      $download = "https://github.com/purescript/purescript/releases/download/$tag/win64.tar.gz"
      Invoke-WebRequest $download -Out purescript.tar.gz
  - tar -xvf purescript.tar.gz
  - chmod a+x purescript

cache:
  - '%STACK_ROOT% -> %STACK_YAML%, appveyor.yml'
  - '.stack-work -> %STACK_YAML%, appveyor.yml'

build_script:
  - stack build
  - stack install --local-bin-path bin
  - cp bin\spago.exe spago.exe
  - tar -zcvf windows.tar.gz spago.exe

test_script:
  - set PATH=C:\projects\spago\bin;C:\projects\spago\purescript;%PATH%
  - set XDG_CACHE_HOME=C:\cache
  - stack test
  # We install psa and rerun the tests that exercise it
  - npm install -g purescript-psa
  - stack test --ta "--match \"/Spago/spago run\""

artifacts:
  - path: windows.tar.gz
    name: spago

deploy:
  - provider: GitHub
    auth_token:
      secure: fJUuBdSozxDLZP2sDiBXf4dEjdSJPBhZvwI/3FII+4RNxow0wGEX5ZzEyeK2wN7q
    artifact: spago
    on:
      APPVEYOR_REPO_TAG: true
