name:                spago
version:             0.10.0.0
github:              "spacchetti/spago"
license:             BSD3
author:              "Justin Woo, Fabrizio Ferrai"
maintainer:          "@jusrin00, @fabferrai"
copyright:           "2018-2019 Justin Woo, Fabrizio Ferrai"

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
  - -Wall

flags:
  static:
    manual: true
    default: false

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/spacchetti/spago#readme>

default-extensions:
- DeriveDataTypeable
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- GeneralizedNewtypeDeriving
- LambdaCase
- RecordWildCards
- ScopedTypeVariables
- OverloadedStrings
- FlexibleContexts
- ConstraintKinds
- NoImplicitPrelude
- ApplicativeDo
- NamedFieldPuns


library:
  source-dirs: src
  dependencies:
  - aeson
  - aeson-pretty
  - ansi-terminal
  - async-pool
  - base >= 4.7 && < 5
  - bower-json
  - bytestring
  - Cabal
  - containers
  - dhall
  - directory >= 1.3.4.0
  - either
  - exceptions
  - file-embed
  - filepath
  - foldl
  - fsnotify
  - github
  - Glob
  - http-client
  - http-conduit
  - lens-family-core
  - mtl
  - network-uri
  - open-browser
  - prettyprinter
  - process
  - retry
  - rio
  - rio-orphans
  - safe
  - semver-range
  - stm
  - tar
  - template-haskell
  - temporary
  - text < 1.3
  - time
  - transformers
  - turtle
  - unliftio
  - unordered-containers
  - vector
  - versions
  - zlib

executables:
  spago:
    main:                Spago.hs
    source-dirs:         app
    other-modules:       [ Paths_spago ]
    when:
    - condition: flag(static)
      then:
        ghc-options:
        - -main-is Spago
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        - -static
        - -O2
        cc-options: -static
        ld-options: -static -pthread
      else:
        ghc-options:
        - -main-is Spago
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - optparse-applicative
    - spago
    - text < 1.3
    - turtle

  spago-curator:
    main:                Curator.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -main-is Curator
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson-pretty
    - async-pool
    - base >= 4.7 && < 5
    - bytestring
    - containers
    - dhall
    - filepath
    - github
    - lens-family-core
    - megaparsec
    - process
    - retry
    - spago
    - stm
    - temporary
    - text < 1.3
    - time
    - turtle
    - vector

tests:
  spec:
    defaults: hspec/hspec@master
    main: Main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - containers
    - directory
    - extra
    - process
    - QuickCheck
    - spago
    - temporary
    - text < 1.3
    - turtle
    - versions
