name:                spago
version:             0.9.0.0
github:              "spacchetti/spago"
license:             BSD3
author:              "Justin Woo, Fabrizio Ferrai"
maintainer:          "@jusrin00, @fabferrai"
copyright:           "2018-2019 Justin Woo, Fabrizio Ferrai"

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
  - -Wall

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/spacchetti/spago#readme>

default-extensions:
- DeriveDataTypeable
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- GeneralizedNewtypeDeriving
- LambdaCase
- RecordWildCards
- ScopedTypeVariables
- OverloadedStrings
- FlexibleContexts
- ConstraintKinds
- NoImplicitPrelude
- ApplicativeDo
- NamedFieldPuns


library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - text < 1.3
  - Cabal
  - turtle
  - either
  - filepath
  - file-embed
  - template-haskell
  - aeson
  - aeson-pretty
  - containers
  - bower-json
  - dhall
  - dhall-json
  - bytestring
  - prettyprinter
  - async-pool
  - process
  - network-uri
  - versions
  - lens-family-core
  - safe
  - fsnotify
  - Glob
  - stm
  - directory
  - mtl
  - exceptions
  - unliftio
  - vector
  - temporary
  - zlib
  - tar
  - foldl
  - http-client
  - http-conduit
  - time
  - either
  - semver-range
  - ansi-terminal
  - unordered-containers
  - retry
  - github

executables:
  spago:
    main:                Spago.hs
    source-dirs:         app
    other-modules:       [ Paths_spago ]
    ghc-options:
    - -main-is Spago
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spago
    - base >= 4.7 && < 5
    - text < 1.3
    - turtle
    - optparse-applicative

  spago-curator:
    main:                Curator.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -main-is Curator
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spago
    - base >= 4.7 && < 5
    - text < 1.3
    - turtle
    - filepath
    - aeson-pretty
    - containers
    - dhall
    - bytestring
    - async-pool
    - process
    - github
    - lens-family-core
    - stm
    - vector
    - temporary
    - retry
    - time

tests:
  spec:
    defaults: hspec/hspec@master
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - text < 1.3
    - turtle
    - process
    - directory
    - temporary
    - extra
    - containers
    - QuickCheck
    - spago
