name:                spago
version:             0.19.2
github:              "purescript/spago"
license:             BSD3
author:              "Justin Woo, Fabrizio Ferrai"
maintainer:          "@jusrin00, @fabferrai"
copyright:           "2018-2020 Justin Woo, Fabrizio Ferrai"

extra-source-files:
- README.md
- CHANGELOG.md
- templates/*

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -fprint-potential-instances
  - -optP-Wno-nonportable-include-path

flags:
  static:
    manual: true
    default: false

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/purescript/spago#readme>

default-extensions:
- ApplicativeDo
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DoAndIfThenElse
- DuplicateRecordFields
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- LiberalTypeSynonyms
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- QuantifiedConstraints
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeSynonymInstances
- UndecidableInstances
- ViewPatterns


library:
  source-dirs: src
  dependencies:
  - aeson
  - aeson-pretty
  - ansi-terminal
  - async-pool
  - base >= 4.7 && < 5
  - bower-json
  - bytestring
  - Cabal
  - containers
  - cryptonite
  - dhall >= 1.31.1
  - directory >= 1.3.4.0
  - either
  - exceptions
  - file-embed
  - filepath
  - foldl
  - fsnotify
  - generic-lens
  - github
  - Glob
  - http-types
  - http-client
  - http-conduit
  - lens-family-core
  - megaparsec >=7.0 && <8.0
  - mtl
  - network-uri
  - open-browser
  - optparse-applicative
  - prettyprinter
  - process
  - retry
  - rio >= 0.1.16.0
  - rio-orphans
  - safe
  - semver-range
  - stm
  - stringsearch
  - tar
  - template-haskell
  - temporary
  - text < 1.3
  - time
  - transformers
  - turtle
  - unliftio
  - unordered-containers
  - utf8-string
  - vector
  - versions
  - with-utf8
  - zlib

executables:
  spago:
    main:                Spago.hs
    source-dirs:         app
    other-modules:       [ Paths_spago ]
    when:
    - condition: flag(static)
      then:
        ghc-options:
        - -main-is Spago
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        - -static
        - -O2
        cc-options: -static
        ld-options: -static -pthread
      else:
        ghc-options:
        - -main-is Spago
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - spago
    - text < 1.3
    - turtle
    - with-utf8

tests:
  spec:
    defaults: hspec/hspec@master
    main: Main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - containers
    - directory
    - extra
    - hspec-megaparsec >=2.0 && <2.1
    - megaparsec >=7.0 && <8.0
    - process
    - QuickCheck
    - spago
    - temporary
    - text < 1.3
    - turtle
    - versions
