name:                spacchetti-cli
version:             0.5.0.0
github:              "justinwoo/spacchetti-cli"
license:             BSD3
author:              "Justin Woo"
maintainer:          "@jusrin00"
copyright:           "2018 Justin Woo"

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
  - -Wall

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/spacchetti-cli#readme>

default-extensions:
- DeriveDataTypeable
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- GeneralizedNewtypeDeriving
- LambdaCase
- RecordWildCards
- ScopedTypeVariables
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- text < 1.3
- turtle
- filepath
- file-embed
- aeson
- aeson-pretty
- containers
- directory
- dhall
- dhall-json
- bytestring
- prettyprinter

executables:
  spacchetti:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  spacchetti-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
