resolver: lts-17.9
packages:
- .
extra-deps:
- dhall-1.38.1
- semver-range-0.2.8
- with-utf8-1.0.2.2
allow-newer: true
nix:
  packages: [zlib]
flags:
  aeson-pretty:
    lib-only: true
  # This is so we don't depend on libtinfo
  haskeline:
    terminfo: false
    examples: false
