on: [ push ]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.4.4'
          stack-version: 'latest'
          enable-stack: true
      - name: Setup node and yarn
        uses: "actions/setup-node@v1"
        with:
          node-version: '10'
      # NB: We install gnu-tar because BSD tar is buggy on Github's macos machines,
      # and it breaks the cache: https://github.com/actions/cache/issues/403
      - name: Install GNU tar (Macos)
        if: runner.os == 'macOS'
        run: |
          brew install gnu-tar
          echo "::add-path::/usr/local/opt/gnu-tar/libexec/gnubin"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-1
          #restore-keys: |
          #  ${{ runner.os }}-
      - run: npm install -g purescript@0.13.8 psc-package@3.0.1 bower@1.8.8
      - run: stack test