name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-16.04, macOS-latest, windows-latest ]
    steps:
      # We set LF endings so that the Windows environment is consistent with Appveyor
      # See here for context: https://github.com/actions/checkout/issues/135
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.6.5'
          stack-version: 'latest'
          enable-stack: true
          stack-no-global: true
          stack-setup-ghc: true
      - name: Setup node and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14
      # NB: We install gnu-tar because BSD tar is buggy on Github's macos machines,
      # and it breaks the cache: https://github.com/actions/cache/issues/403
      - name: Install GNU tar (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gnu-tar
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH
      - name: create ~/.local/bin
        run: mkdir -p "$HOME/.local/bin"
      - name: Add ~/.local/bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-1
      - run: npm install -g purescript@0.13.8 psc-package@3.0.1 bower@1.8.8

      - name: Install dependencies
        run: |
          stack install --dependencies-only
        shell: bash

      - name: Build
        run: stack build
        shell: bash

      - name: Install
        run: stack install
        shell: bash

      - name: Run tests
        run: stack test
        shell: bash